name: Deploy Site

on:
  push:
    branches:
      - master # only run this workflow when there's a new commit pushed to the master branch

jobs:
  deploy: # job_id
    runs-on: ubuntu-latest # environment: use ubuntu

    steps: # automated steps
      - name: Checkout Repo # 1. checkout repo
        uses: actions/checkout@v2 # Use a third party action (https://github.com/actions/checkout)

      - name: start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PEM }}
          script: |
            cd ~/myblogs
            git pull
            cd /root/www/myHexoBlog/blog/source/_posts
            rm -f *.md
            cp -r ~/myblogs/*.md .
            rm -f README.md
            cd /root/www/myHexoBlog/blog
            chmod +x ~/myblogs/run.sh
            ./run.sh
