name: Deploy Site

on:
  push:
    branches:
      - master # only run this workflow when there's a new commit pushed to the master branch

jobs:
  deploy: # job_id
    runs-on: ubuntu-latest # environment: use ubuntu

    steps: # automated steps
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: myblogs
      - name: Checkout blog source code
        uses: actions/checkout@v2
        with:
          repository: LesterHoly/myHexoBlog
          token: ${{ secrets.TOKEN }}
          path: myHexoBlog
      - name: Checkout static
        uses: actions/checkout@v2
        with:
          repository: LesterHoly/myblogs_static
          token: ${{ secrets.TOKEN }}
          path: myblogs_static
      - name: Setup hexo environment
        run: |
         cd myHexoBlog/blog
          npm install -g hexo-cli
          npm install
      - name: Generate Public
        run: |
          rm -f myHexoBlog/blog/source/_posts/*.md
          cp -r myblogs/*.md myHexoBlog/blog/source/_posts/
          rm -f myHexoBlog/blog/source/_posts/README.md
          cd myHexoBlog/blog
          echo "run hexo"
          hexo clean
          hexo g
          cp -r ./public myblogs_static
      - name: Commit files
        run: |
          cd myblogs_static
          git config --local user.email ${{ secrets.USER_NAME }}
          git config --local user.name ${{ secrets.EMAIL }}
          git add --all
          git commit -m "Update static by github bot" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: "main"
