name: Deploy Site

on:
  push:
    branches:
      - master # only run this workflow when there's a new commit pushed to the master branch

jobs:
  deploy: # job_id
    runs-on: ubuntu-latest # environment: use ubuntu

    steps: # automated steps
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: myblogs
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: LesterHoly/myHexoBlog
          token: ${{ secrets.TOKEN }}
          path: myHexoBlog
      - name: Setup hexo environment
        run: |
         cd myHexoBlog/blog
          npm install -g hexo-cli
          npm install
      - name: Generate Public
        run: |
          rm -f myHexoBlog/blog/source/_posts/*.md
          cp -r myblogs/*.md myHexoBlog/blog/source/_posts/
          rm -f myHexoBlog/blog/source/_posts/README.md
          cd myHexoBlog/blog
          echo "run hexo"
          hexo clean
          hexo g
          pwd
          ls ./public
          cp -r ./public ~
#         scp -i ${{ secrets.PEM }}  -P ${{ secrets.PORT }} -r ./public ${{ secrets.USER }}@${{ secrets.HOST }}:/root/
#       - name: SCP Public
#         run: |
#           cd /home/runner/work/myHexoBlog/blog
#           scp -i ${{ secrets.PEM }}  -P ${{ secrets.PORT }} -r public ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.PUBLIC_PATH }}
